# Solar Power Generation and Plant Performance Analyzer

## Objective

The goal of this notebook is to prepare the raw solar power generation and weather datasets for analysis and machine learning.

The tasks performed in this notebook include:

- Loading the raw datasets
- Inspecting data quality
- Handling missing values and duplicates
- Converting data types
- Merging generation and weather datasets
- Saving a cleaned dataset for downstream analysis

The processed dataset generated in this notebook will be used throughout the rest of the project.

In [6]:

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [8]:

plant1_gen = pd.read_csv("Plant_1_Generation_Data.csv")
plant1_weather = pd.read_csv("Plant_1_Weather_Sensor_Data.csv")
plant2_gen = pd.read_csv("Plant_2_Generation_Data.csv")
plant2_weather = pd.read_csv("Plant_2_Weather_Sensor_Data.csv")

In [9]:
def dataset_overview(df, name):

    print("="*70)
    print(name)
    print("="*70)

    print(f"Shape : {df.shape}")

    print("\nColumns")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nFirst Five Rows")
    display(df.head())

In [10]:
dataset_overview(plant1_gen,"Plant 1 Generation")
dataset_overview(plant1_weather,"Plant 1 Weather")

dataset_overview(plant2_gen,"Plant 2 Generation")
dataset_overview(plant2_weather,"Plant 2 Weather")

======================================================================
Plant 1 Generation
======================================================================
Shape : (68778, 7)

Columns
['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD', 'TOTAL_YIELD']

Data Types
DATE_TIME       object
PLANT_ID         int64
SOURCE_KEY      object
DC_POWER       float64
AC_POWER       float64
DAILY_YIELD    float64
TOTAL_YIELD    float64
dtype: object

Missing Values
DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

Duplicate Rows
0

First Five Rows

          DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  DAILY_YIELD  TOTAL_YIELD
0  15-05-2020 00:00   4135001  1BY6WEcLGh8j5v7       0.0       0.0          0.0    6259559.0
1  15-05-2020 00:00   4135001  1IF53ai7Xc0U56Y       0.0       0.0          0.0    6183645.0
2  15-05-2020 00:00   4135001  3PZuoBAID5Wc2HD       0.0       0.0          0.0    6987759.0
3  15-05-2020 00:00   4135001  7JYdWkrLSPkdwr4       0.0       0.0          0.0    7602960.0
4  15-05-2020 00:00   4135001  McdE0feGgRqW7Ca       0.0       0.0          0.0    7158964.0

======================================================================
Plant 1 Weather
======================================================================
Shape : (3182, 6)

Columns
['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION']

Data Types
DATE_TIME               object
PLANT_ID                 int64
SOURCE_KEY              object
AMBIENT_TEMPERATURE    float64
MODULE_TEMPERATURE     float64
IRRADIATION            float64
dtype: object

Missing Values
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

Duplicate Rows
0

First Five Rows

             DATE_TIME  PLANT_ID       SOURCE_KEY  AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION
0  2020-05-15 00:00:00   4135001  HmiyD2TTLFNqkNe            25.184316           22.857507          0.0
1  2020-05-15 00:15:00   4135001  HmiyD2TTLFNqkNe            25.084589           22.761668          0.0
2  2020-05-15 00:30:00   4135001  HmiyD2TTLFNqkNe            24.935753           22.592306          0.0
3  2020-05-15 00:45:00   4135001  HmiyD2TTLFNqkNe            24.846130           22.360852          0.0
4  2020-05-15 01:00:00   4135001  HmiyD2TTLFNqkNe            24.621525           22.165423          0.0

======================================================================
Plant 2 Generation
======================================================================
Shape : (67698, 7)

Columns
['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD', 'TOTAL_YIELD']

Data Types
DATE_TIME       object
PLANT_ID         int64
SOURCE_KEY      object
DC_POWER       float64
AC_POWER       float64
DAILY_YIELD    float64
TOTAL_YIELD    float64
dtype: object

Missing Values
DATE_TIME      0
PLANT_ID       0
SOURCE_KEY     0
DC_POWER       0
AC_POWER       0
DAILY_YIELD    0
TOTAL_YIELD    0
dtype: int64

Duplicate Rows
0

First Five Rows

             DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  DAILY_YIELD   TOTAL_YIELD
0  2020-05-15 00:00:00   4136001  4UPUqMRk7TRMgml       0.0       0.0  9425.000000  2.429011e+06
1  2020-05-15 00:00:00   4136001  81aHJ1q11NBPMrL       0.0       0.0     0.000000  1.215279e+09
2  2020-05-15 00:00:00   4136001  9kRcWv60rDACzjR       0.0       0.0  3075.333333  2.247720e+09
3  2020-05-15 00:00:00   4136001  Et9kgGMDl729KT4       0.0       0.0   269.933333  1.704250e+06
4  2020-05-15 00:00:00   4136001  IQ2d7wF4YD8zU1Q       0.0       0.0  3177.000000  1.994153e+07

======================================================================
Plant 2 Weather
======================================================================
Shape : (3259, 6)

Columns
['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION']

Data Types
DATE_TIME               object
PLANT_ID                 int64
SOURCE_KEY              object
AMBIENT_TEMPERATURE    float64
MODULE_TEMPERATURE     float64
IRRADIATION            float64
dtype: object

Missing Values
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
AMBIENT_TEMPERATURE    0
MODULE_TEMPERATURE     0
IRRADIATION            0
dtype: int64

Duplicate Rows
0

First Five Rows

             DATE_TIME  PLANT_ID       SOURCE_KEY  AMBIENT_TEMPERATURE  MODULE_TEMPERATURE  IRRADIATION
0  2020-05-15 00:00:00   4136001  iq8k7ZNt4Mwm3w0            27.004764           25.060789          0.0
1  2020-05-15 00:15:00   4136001  iq8k7ZNt4Mwm3w0            26.880811           24.421869          0.0
2  2020-05-15 00:30:00   4136001  iq8k7ZNt4Mwm3w0            26.682055           24.427290          0.0
3  2020-05-15 00:45:00   4136001  iq8k7ZNt4Mwm3w0            26.500589           24.420678          0.0
4  2020-05-15 01:00:00   4136001  iq8k7ZNt4Mwm3w0            26.596148           25.088210          0.0

In [11]:
datasets = [
    plant1_gen,
    plant1_weather,
    plant2_gen,
    plant2_weather
]

for df in datasets:
    df["DATE_TIME"] = pd.to_datetime(df["DATE_TIME"])

In [12]:
quality_report = pd.DataFrame()

for name, df in {
    "Plant1_Generation": plant1_gen,
    "Plant1_Weather": plant1_weather,
    "Plant2_Generation": plant2_gen,
    "Plant2_Weather": plant2_weather
}.items():

    quality_report.loc[name,"Rows"] = df.shape[0]
    quality_report.loc[name,"Columns"] = df.shape[1]
    quality_report.loc[name,"Missing"] = df.isnull().sum().sum()
    quality_report.loc[name,"Duplicates"] = df.duplicated().sum()

In [13]:
quality_report

                      Rows  Columns  Missing  Duplicates
Plant1_Generation  68778.0      7.0      0.0         0.0
Plant1_Weather      3182.0      6.0      0.0         0.0
Plant2_Generation  67698.0      7.0      0.0         0.0
Plant2_Weather      3259.0      6.0      0.0         0.0

In [14]:
# ============================================================
# Data Validation
# ============================================================

def validate_data(df, name):

    print("="*70)
    print(name)
    print("="*70)

    print("Negative DC_POWER:",
          (df["DC_POWER"] < 0).sum() if "DC_POWER" in df.columns else "N/A")

    print("Negative AC_POWER:",
          (df["AC_POWER"] < 0).sum() if "AC_POWER" in df.columns else "N/A")

    print("Negative DAILY_YIELD:",
          (df["DAILY_YIELD"] < 0).sum() if "DAILY_YIELD" in df.columns else "N/A")

    print("Negative IRRADIATION:",
          (df["IRRADIATION"] < 0).sum() if "IRRADIATION" in df.columns else "N/A")

    print("Ambient Temp < -20:",
          (df["AMBIENT_TEMPERATURE"] < -20).sum()
          if "AMBIENT_TEMPERATURE" in df.columns else "N/A")

    print("Module Temp < -20:",
          (df["MODULE_TEMPERATURE"] < -20).sum()
          if "MODULE_TEMPERATURE" in df.columns else "N/A")

In [15]:
validate_data(plant1_gen, "Plant 1 Generation")
validate_data(plant2_gen, "Plant 2 Generation")

validate_data(plant1_weather, "Plant 1 Weather")
validate_data(plant2_weather, "Plant 2 Weather")

======================================================================
Plant 1 Generation
======================================================================
Negative DC_POWER: 0
Negative AC_POWER: 0
Negative DAILY_YIELD: 0
Negative IRRADIATION: N/A
Ambient Temp < -20: N/A
Module Temp < -20: N/A
======================================================================
Plant 2 Generation
======================================================================
Negative DC_POWER: 0
Negative AC_POWER: 0
Negative DAILY_YIELD: 0
Negative IRRADIATION: N/A
Ambient Temp < -20: N/A
Module Temp < -20: N/A
======================================================================
Plant 1 Weather
======================================================================
Negative DC_POWER: N/A
Negative AC_POWER: N/A
Negative DAILY_YIELD: N/A
Negative IRRADIATION: 0
Ambient Temp < -20: 0
Module Temp < -20: 0
======================================================================
Plant 2 Weather
======================================================================
Negative DC_POWER: N/A
Negative AC_POWER: N/A
Negative DAILY_YIELD: N/A
Negative IRRADIATION: 0
Ambient Temp < -20: 0
Module Temp < -20: 0

In [16]:
def date_range(df,name):

    print("="*80)
    print(name)
    print("="*80)

    print("Start Date :",df["DATE_TIME"].min())
    print("End Date   :",df["DATE_TIME"].max())
    print("Number of Records :",len(df))
    print()


date_range(plant1_gen,"Plant 1 Generation")
date_range(plant1_weather,"Plant 1 Weather")

date_range(plant2_gen,"Plant 2 Generation")
date_range(plant2_weather,"Plant 2 Weather")

================================================================================
Plant 1 Generation
================================================================================
Start Date : 2020-05-15 00:00:00
End Date   : 2020-06-17 23:45:00
Number of Records : 68778

================================================================================
Plant 1 Weather
================================================================================
Start Date : 2020-05-15 00:00:00
End Date   : 2020-06-17 23:45:00
Number of Records : 3182

================================================================================
Plant 2 Generation
================================================================================
Start Date : 2020-05-15 00:00:00
End Date   : 2020-06-17 23:45:00
Number of Records : 67698

================================================================================
Plant 2 Weather
================================================================================
Start Date : 2020-05-15 00:00:00
End Date   : 2020-06-17 23:45:00
Number of Records : 3259

In [ ]:
print("="*80)
print("Plant Summary")
print("="*80)

print("\nPlant 1")
print("Plant ID :",plant1_gen["PLANT_ID"].unique()[0])
print("Generation Inverters :",plant1_gen["SOURCE_KEY"].nunique())
print("Weather Sensors :",plant1_weather["SOURCE_KEY"].nunique())

print("\nPlant 2")
print("Plant ID :",plant2_gen["PLANT_ID"].unique()[0])
print("Generation Inverters :",plant2_gen["SOURCE_KEY"].nunique())
print("Weather Sensors :",plant2_weather["SOURCE_KEY"].nunique())

In [17]:
# =============================================================================
# 10. Merge Plant 1
# =============================================================================

plant1 = pd.merge(
    plant1_gen,
    plant1_weather.drop(columns=["SOURCE_KEY"]),
    on=["DATE_TIME","PLANT_ID"],
    how="left"
)

plant1["PLANT_NAME"] = "Plant_1"


# =============================================================================
# 11. Merge Plant 2
# =============================================================================

plant2 = pd.merge(
    plant2_gen,
    plant2_weather.drop(columns=["SOURCE_KEY"]),
    on=["DATE_TIME","PLANT_ID"],
    how="left"
)

plant2["PLANT_NAME"] = "Plant_2"


# =============================================================================
# 12. Combine Both Plants
# =============================================================================

solar_complete = pd.concat(
    [plant1,plant2],
    ignore_index=True
)

print("="*80)
print("Merged Dataset")
print("="*80)

print("Shape :",solar_complete.shape)

display(solar_complete.head())

================================================================================
Merged Dataset
================================================================================
Shape : (136476, 11)

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,PLANT_NAME
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,Plant_1
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,Plant_1
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,Plant_1
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,Plant_1
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,Plant_1

In [19]:
# =============================================================================
# 13. Final Validation
# =============================================================================

print("=" * 80)
print("FINAL DATASET VALIDATION")
print("=" * 80)

print("\nDataset Information\n")
solar_complete.info()

print("\n" + "=" * 80)
print("Missing Values")
print("=" * 80)
print(solar_complete.isnull().sum())

print("\nTotal Missing Values :", solar_complete.isnull().sum().sum())

print("\n" + "=" * 80)
print("Duplicate Records")
print("=" * 80)
print("Duplicate Rows :", solar_complete.duplicated().sum())

print("\n" + "=" * 80)
print("Preview of Processed Dataset")
print("=" * 80)
display(solar_complete.head())


# =============================================================================
# 14. Save Processed Dataset
# =============================================================================

import os

# Create processed folder if it does not exist
os.makedirs("../data/processed", exist_ok=True)

plant1_path = "../data/processed/plant1_clean.csv"
plant2_path = "../data/processed/plant2_clean.csv"
solar_path = "../data/processed/solar_complete.csv"

plant1.to_csv(plant1_path, index=False)
plant2.to_csv(plant2_path, index=False)
solar_complete.to_csv(solar_path, index=False)

print("\nDatasets saved successfully!")

print("\nSaved Files")
print("-" * 40)
print(f"Plant 1 Dataset : {plant1_path}")
print(f"Plant 2 Dataset : {plant2_path}")
print(f"Combined Dataset: {solar_path}")


# =============================================================================
# 15. Verify Saved Dataset
# =============================================================================

print("\n" + "=" * 80)
print("VERIFY SAVED DATASET")
print("=" * 80)

saved_dataset = pd.read_csv(solar_path)

print(f"Saved Dataset Shape : {saved_dataset.shape}")

if saved_dataset.shape == solar_complete.shape:
    print("Dataset verification successful.")
else:
    print("Warning: Saved dataset shape does not match.")


# =============================================================================
# 16. Notebook Summary
# =============================================================================

print("\n" + "=" * 80)
print("NOTEBOOK 01 SUMMARY")
print("=" * 80)

summary = pd.DataFrame({
    "Metric": [
        "Raw Datasets Loaded",
        "Generation Datasets",
        "Weather Datasets",
        "Merged Dataset Created",
        "Final Dataset Rows",
        "Final Dataset Columns",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Value": [
        4,
        2,
        2,
        "Yes",
        solar_complete.shape[0],
        solar_complete.shape[1],
        solar_complete.isnull().sum().sum(),
        solar_complete.duplicated().sum()
    ]
})

display(summary)

print("\nOutput Files")
print("-" * 40)
print("✓ plant1_clean.csv")
print("✓ plant2_clean.csv")
print("✓ solar_complete.csv")

print("\nNext Notebook")
print("-" * 40)
print("Notebook 02 : Exploratory Data Analysis (EDA)")

print("\nNotebook 01 completed successfully!")

================================================================================
FINAL DATASET VALIDATION
================================================================================

Dataset Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136476 entries, 0 to 136475
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   DATE_TIME            136476 non-null  datetime64[ns]
 1   PLANT_ID             136476 non-null  int64
 2   SOURCE_KEY           136476 non-null  object
 3   DC_POWER             136476 non-null  float64
 4   AC_POWER             136476 non-null  float64
 5   DAILY_YIELD          136476 non-null  float64
 6   TOTAL_YIELD          136476 non-null  float64
 7   AMBIENT_TEMPERATURE  136472 non-null  float64
 8   MODULE_TEMPERATURE   136472 non-null  float64
 9   IRRADIATION          136472 non-null  float64
 10  PLANT_NAME           136476 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(1), object(2)
memory usage: 11.5+ MB

================================================================================
Missing Values
================================================================================
DATE_TIME              0
PLANT_ID               0
SOURCE_KEY             0
DC_POWER               0
AC_POWER               0
                      ..
TOTAL_YIELD            0
AMBIENT_TEMPERATURE    4
MODULE_TEMPERATURE     4
IRRADIATION            4
PLANT_NAME             0
Length: 11, dtype: int64

Total Missing Values : 12

================================================================================
Duplicate Records
================================================================================
Duplicate Rows : 0

================================================================================
Preview of Processed Dataset
================================================================================

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION,PLANT_NAME
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,25.184316,22.857507,0.0,Plant_1
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,25.184316,22.857507,0.0,Plant_1
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,25.184316,22.857507,0.0,Plant_1
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,25.184316,22.857507,0.0,Plant_1
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,25.184316,22.857507,0.0,Plant_1

Datasets saved successfully!

Saved Files
----------------------------------------
Plant 1 Dataset : ../data/processed/plant1_clean.csv
Plant 2 Dataset : ../data/processed/plant2_clean.csv
Combined Dataset: ../data/processed/solar_complete.csv

================================================================================
VERIFY SAVED DATASET
================================================================================
Saved Dataset Shape : (136476, 11)
Dataset verification successful.

================================================================================
NOTEBOOK 01 SUMMARY
================================================================================

                   Metric   Value
0     Raw Datasets Loaded       4
1     Generation Datasets       2
2        Weather Datasets       2
3  Merged Dataset Created     Yes
4      Final Dataset Rows  136476
5   Final Dataset Columns      11
6          Missing Values      12
7          Duplicate Rows       0

Output Files
----------------------------------------
✓ plant1_clean.csv
✓ plant2_clean.csv
✓ solar_complete.csv

Next Notebook
----------------------------------------
Notebook 02 : Exploratory Data Analysis (EDA)

Notebook 01 completed successfully!

In [21]:
# =============================================================================
# Handle Missing Values After Merge
# =============================================================================

print("=" * 80)
print("Handling Missing Values")
print("=" * 80)

print(f"Rows Before Cleaning : {solar_complete.shape[0]}")

missing_rows = solar_complete.isnull().any(axis=1).sum()

print(f"Rows with Missing Values : {missing_rows}")

# Remove rows with missing weather information
solar_complete = solar_complete.dropna().reset_index(drop=True)

print(f"Rows After Cleaning : {solar_complete.shape[0]}")

print(f"Remaining Missing Values : {solar_complete.isnull().sum().sum()}")


# =============================================================================
# Final Integrity Check
# =============================================================================

assert solar_complete.isnull().sum().sum() == 0
assert solar_complete.duplicated().sum() == 0

print("All integrity checks passed.")

================================================================================
Handling Missing Values
================================================================================
Rows Before Cleaning : 136476
Rows with Missing Values : 4
Rows After Cleaning : 136472
Remaining Missing Values : 0
All integrity checks passed.

In [23]:
import os

# --- Configurations ---
GITHUB_USERNAME = "cain0393-cmd"
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"
REPO_NAME = "Solar-Power-Generation-and-Plant-Performance-Analyzer"
USER_EMAIL = "cain0393@gmail.com"
USER_NAME = "cain0393-cmd"

# Clone the repository
!git clone https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

# Change working directory into the cloned repository
%cd {REPO_NAME}

# Set Git user identity
!git config user.email "{USER_EMAIL}"
!git config user.name "{USER_NAME}"

Cloning into 'Solar-Power-Generation-and-Plant-Performance-Analyzer'...
warning: You appear to have cloned an empty repository.
/content/Solar-Power-Generation-and-Plant-Performance-Analyzer

In [25]:
import os

# List of all directories to create
directories = [
    "data/raw",
    "data/processed",
    "notebooks",
    "src",
    "app",
    "models",
    "reports/figures"
]

# List of root/nested placeholder files
files = [
    "notebooks/01_Data_Preparation.ipynb",
    "notebooks/02_EDA.ipynb",
    "notebooks/03_Feature_Engineering.ipynb",
    "notebooks/04_Model_Training.ipynb",
    "notebooks/05_Model_Evaluation.ipynb",
    "src/preprocessing.py",
    "src/eda.py",
    "src/feature_engineering.py",
    "src/model.py",
    "src/utils.py",
    "app/app.py",
    "reports/report.pdf",
    "requirements.txt",
    "README.md",
    "LICENSE",
    ".gitignore"
]

# 1. Create directories and add .gitkeep to keep empty ones tracked
for d in directories:
    os.makedirs(d, exist_ok=True)
    gitkeep_path = os.path.join(d, ".gitkeep")
    if not os.path.exists(gitkeep_path):
        with open(gitkeep_path, "w") as f:
            pass  # Creates an empty .gitkeep file

# 2. Touch placeholder files if they don't exist yet
for filepath in files:
    if not os.path.exists(filepath):
        # Create missing parent folder if needed
        os.makedirs(os.path.dirname(filepath), exist_ok=True) if os.path.dirname(filepath) else None
        with open(filepath, "w") as f:
            if filepath == ".gitignore":
                f.write("# Ignore raw data and virtual environments\n__pycache__/\n*.pyc\n.ipynb_checkpoints/\n")
            elif filepath == "README.md":
                f.write("# Solar Power Generation Analyzer\n")

print("Directory structure created successfully!")

Directory structure created successfully!

In [26]:
# Copy raw CSVs into data/raw/
!cp ../Plant_1_Generation_Data.csv data/raw/ 2>/dev/null || true
!cp ../Plant_1_Weather_Sensor_Data.csv data/raw/ 2>/dev/null || true
!cp ../Plant_2_Generation_Data.csv data/raw/ 2>/dev/null || true
!cp ../Plant_2_Weather_Sensor_Data.csv data/raw/ 2>/dev/null || true

# Copy current notebook into notebooks/01_Data_Preparation.ipynb
# (Colab saves notebooks in drive or local runtime; if running locally in colab, save a copy directly)

In [29]:
GITHUB_USERNAME = "cain0393-cmd"
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"
REPO_NAME = "Solar-Power-Generation-and-Plant-Performance-Analyzer"

# Update remote URL with the new token
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git

# Push to GitHub
!git push -u origin main

Branch 'main' set up to track remote branch 'main' from 'origin'.
Everything up-to-date

In [30]:
import os

# --- Credentials ---
GITHUB_USERNAME = "cain0393-cmd"
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"  # Make sure this starts with github_pat_
REPO_NAME = "Solar-Power-Generation-and-Plant-Performance-Analyzer"

# 1. Ensure local branch name is set to 'main'
!git branch -M main

# 2. Reset the remote URL completely with embedded token credentials
remote_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"
!git remote remove origin 2>/dev/null || true
!git remote add origin {remote_url}

# 3. Force push to main
!git push -u origin main --force

Branch 'main' set up to track remote branch 'main' from 'origin'.
Everything up-to-date

In [ ]:
import os
import json
import re
from google.colab import _message

# --- Set credentials in memory/environment ONLY ---
GITHUB_USERNAME = "cain0393-cmd"
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN"   # Token is passed dynamically, not saved to notebook
REPO_NAME = "Solar-Power-Generation-and-Plant-Performance-Analyzer"
repo_path = f"/content/{REPO_NAME}"

# 1. Reset local git commit to erase the secret from local git history
%cd {repo_path}
!git reset HEAD~1

# 2. Get active notebook content
notebook_json = _message.blocking_request('get_ipynb')['ipynb']
notebook_str = json.dumps(notebook_json)

# 3. Regex strip any token patterns (ghp_... or github_pat_...) from the notebook JSON
cleaned_notebook_str = re.sub(r'github_pat_[a-zA-Z0-9_]+', 'YOUR_GITHUB_TOKEN', notebook_str)
cleaned_notebook_str = re.sub(r'ghp_[a-zA-Z0-9]+', 'YOUR_GITHUB_TOKEN', cleaned_notebook_str)

# 4. Save cleaned notebook back to repo path
notebook_target_path = os.path.join(repo_path, "notebooks/01_Data_Preparation.ipynb")
with open(notebook_target_path, 'w', encoding='utf-8') as f:
    f.write(cleaned_notebook_str)

# 5. Re-stage, commit, and push clean version
!git add notebooks/01_Data_Preparation.ipynb
!git commit -m "Upload 01_Data_Preparation.ipynb (sanitized)"

# Push via authenticated URL using the token from variable
!git remote set-url origin https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git
!git push origin main

/content/Solar-Power-Generation-and-Plant-Performance-Analyzer
Unstaged changes after reset:
M	notebooks/01_Data_Preparation.ipynb